### ISSUE TITLE
添加迁移所必须的几个元数据

### ISSUE THREAD

**Issue by sghng** [SUSTech-Application/SUSTechapplication#162]
分为两类，第一类是不影响功能，但依赖于文件名，因此要在迁移之前做好：

- [x] 地区（可以先直接填写，具体的值以后再讨论，这不影响现在的功能）
- [x] 年级（不影响功能）

第二类是功能也依赖于这些元数据

- [x] 日期（实现排序）
- [x] 专业/院系（sidebar 依赖于此，需要较多讨论）
- [x] 标题（需要从元数据中取得标题来渲染）

以及

- [x] 类型 `type` 或者 `category`

为了实现 #160，需要将上述几个元数据添加到 YAML frontmatter 中。

**Comment by sghuang19** [comment]
提议的元数据组织方式，key 基本上是确定的，只有 department / major 还需要讨论

```yaml
title: ... # 可以从一级标题中提取
date: 2025-01-01
department: cse ""
region: us # 需要参考现在已有的地区代码
year: 19
```
